[package]
name = "henkan"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.61"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse"
]

[dependencies]
ctrlc = "3.4"
